image: ghcr.io/sikalabs/ci

variables:
  IMAGE_BACKEND: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG
  IMAGE_FRONTEND: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG

stages:
  - build
  - test

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

build:
  stage: build
  script:
    - docker compose build
    - docker compose push

test:
  variables:
    COMPOSE_PROJECT_NAME: counter_$CI_JOB_ID
  parallel:
    matrix:
      - TEST:
          - tests
          - ab-be-api
          - ab-be
          - ab-fe
  script:
    - make use-tests
    - docker compose pull
    - docker compose run $TEST
  after_script:
    - docker compose down
